// Generated by https://quicktype.io

import { Celula } from "./celula.interface";
import { Postulante } from "./postulante.interface";
import { Rol } from "./rol.interface";

export interface Proceso {
    id:                 number;
    fecha_ingreso:      string;
    comentariosPrueba:  string;
    puntajePrueba:      number;
    postulante:         Postulante;
    rol:                Rol;
    celula:             Celula;
}

