// Generated by https://quicktype.io

export interface Postulante {
    id:           number;
    nombres:      string;
    apellidos:    string;
    ciudad:       string;
    enlaceBizneo: string;
}
